update ci pipeline

diff --git a/ci/scripts/testflight b/ci/scripts/testflight
--- a/ci/scripts/testflight
+++ b/ci/scripts/testflight
@@ -1,4 +1,10 @@
 #!/bin/bash
+#
+# ci/scripts/testflight
+#
+# Script for testing a BOSH release using bosh2
+#
+# author:  James Hunt <james@niftylogic.com>
 
 header() {
 	echo
@@ -12,15 +18,50 @@ header() {
 
 set -e
 
-export BOSH_ENVIRONMENT=${BOSH_ENVIRONMENT:?required}
-export BOSH_CA_CERT=${BOSH_CA_CERT:?required}
-export BOSH_CLIENT=${BOSH_CLIENT:?required}
-export BOSH_CLIENT_SECRET=${BOSH_CLIENT_SECRET:?required}
-export BOSH_DEPLOYMENT=${BOSH_DEPLOYMENT:?required}
+: ${BOSH_ENVIRONMENT:?required}
+: ${BOSH_CA_CERT:?required}
+: ${BOSH_CLIENT:?required}
+: ${BOSH_CLIENT_SECRET:?required}
+: ${BOSH_DEPLOYMENT:?required}
+: ${MANIFEST_PATH:?required}
 
-cd ${REPO_ROOT}
+cd ${REPO_ROOT:?required}
 header "Pulling in any git submodules..."
 git submodule update --init --recursive --force
+
+header "Confirming testflight inputs"
+
+echo "Confirming deployment manifest ${MANIFEST_PATH} exists"
+if [[ ! -f ${MANIFEST_PATH} ]]; then
+	echo "Deployment manifest ${MANIFEST_PATH} does not exist"
+	exit 1
+fi
+
+echo "Confirming that \$MANIFEST_VARS is valid"
+mkdir -p tmp
+
+# $MANIFEST_VARS can either be "key: value" or "key=value"
+# and will be converted to "key: value" YAML
+echo "${MANIFEST_VARS:-"{} ---"}" | sed -e "s/ *= */: /g" > tmp/vars.yml
+if [[ ! -z $DEBUG ]]; then
+	echo "Variables passed to deployment manifest:"
+	cat tmp/vars.yml
+fi
+# convert YAML to JSON to check YAML validity
+spruce json tmp/vars.yml > /dev/null
+
+echo "Confirming each operator file exists: ${MANIFEST_OP_PATHS:-ok, none specified.}"
+op_patch_file_errors=
+for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
+	if [[ ! -f $op_patch_file ]]; then
+		op_patch_file_errors=1
+		echo "Operator file missing: ${op_patch_file}"
+	fi
+done
+if [[ ! -z ${op_patch_file_errors} ]]; then
+	exit 1
+fi
+
 
 header "Cleaning up from any previous deployments..."
 bosh2 -n delete-deployment
@@ -37,8 +78,6 @@ vm_type=$(bosh2 int <(bosh2 cloud-config) --path /vm_types/0/name)
 disk_type=$(bosh2 int <(bosh2 cloud-config) --path /disk_types/0/name)
 network=$(bosh2 int <(bosh2 cloud-config) --path /networks/0/name)
 
-mkdir -p tmp
-
 cat > tmp/deployment.yml <<YAML
 ---
 - type: replace
@@ -46,30 +85,36 @@ cat > tmp/deployment.yml <<YAML
   value: ${BOSH_DEPLOYMENT}
 
 - type: replace
-  path: /instance_groups/name=shield/vm_type
+  path: /releases/name=${release_name}
+  value:
+    name: ${release_name}
+    version: latest
+YAML
+
+for ig_name in $(spruce json ${MANIFEST_PATH} | jq -r ".instance_groups[].name"); do
+cat >> tmp/deployment.yml <<YAML
+- type: replace
+  path: /instance_groups/name=${ig_name}/vm_type
   value: ${vm_type}
 
 - type: replace
-  path: /instance_groups/name=shield/persistent_disk_type
+  path: /instance_groups/name=${ig_name}/persistent_disk_type?
   value: ${disk_type}
 
 - type: replace
-  path: /instance_groups/name=shield/networks
+  path: /instance_groups/name=${ig_name}/networks
   value: [{name: ${vm_type}}]
 YAML
-
-cat > tmp/vars.yml <<YAML
---- {}
-YAML
+done
 
 op_patch_files_flags=""
-for op_patch_file in ${op_patch_files//,/ } ; do
+for op_patch_file in ${MANIFEST_OP_PATHS//,/ } ; do
    op_patch_files_flags="${op_patch_files_flags} -o $op_patch_file"
 done
 
 set -x
-bosh2 int ${base_manifest:?required} \
-  -o manifests/operators/dev.yml  \
+
+bosh2 int ${MANIFEST_PATH} \
   -o tmp/deployment.yml    \
   ${op_patch_files_flags}            \
   --vars-store tmp/creds.yml \
@@ -78,6 +123,17 @@ bosh2 int ${base_manifest:?required} \
     > tmp/manifest.yml
 
 bosh2 -n deploy tmp/manifest.yml
+
+TEST_ERRAND=${TEST_ERRAND:-} # backwards compatibility
+TEST_ERRANDS=${TEST_ERRANDS:-$TEST_ERRAND}
+if [[ -n ${TEST_ERRANDS} ]]; then
+	for errand in ${TEST_ERRANDS}; do
+		header "Running '${errand}' errand"
+		bosh2 -n run-errand ${errand}
+	done
+else
+	echo "No test errands specified, skipping."
+fi
 
 echo
 echo "SUCCESS"
