Fixed STEMCELL_URLs

diff --git a/templates/make_manifest b/templates/make_manifest
--- a/templates/make_manifest
+++ b/templates/make_manifest
@@ -7,11 +7,25 @@ STEMCELL_OS=${STEMCELL_OS:-ubuntu}
 
 infrastructure=$1
 
-if [ "$infrastructure" != "aws-ec2" ] && \
+fail() {
+	echo >&2 $*
+}
+
+if [ "$infrastructure" != "aws" ] && \
     [ "$infrastructure" != "warden" ] ; then
-  echo "usage: ./make_manifest <aws-ec2|warden>"
+  echo "usage: ./make_manifest <aws|warden> <ubuntu|centos>"
   exit 1
 fi
+
+case "${infrastructure}/${STEMCELL_OS}" in
+  (warden/*)   STEMCELL_URL="https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent" ;;
+  (aws/ubuntu) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-ubuntu-trusty-go_agent" ;;
+  (aws/centos) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-centos-7-go_agent" ;;
+  (*)
+    fail "Invalid infrastructure or OS specified."
+    exit 1
+    ;;
+esac
 
 shift
 
@@ -21,18 +35,14 @@ DIRECTOR_CPI=$(echo "$BOSH_STATUS" | grep CPI | awk '{print $2}' | sed -e 's/_cp
 DIRECTOR_NAME=$(echo "$BOSH_STATUS" | grep Name | awk '{print $2}')
 NAME=$template_prefix-$infrastructure
 
-if [[ $DIRECTOR_NAME = "warden" ]]; then
-  if [[ $infrastructure != "warden" ]]; then
-    echo "Not targeting bosh-lite with warden CPI. Please use 'bosh target' before running this script."
-    exit 1
-  fi
+if [[ $DIRECTOR_NAME = "warden" && ${infrastructure} != "warden" ]]; then
+  fail "Not targeting bosh-lite with warden CPI. Please make sure you have run 'bosh target' and are targeting a BOSH lite before running this script."
+  exit 1
 fi
 
-if [[ $infrastructure = "aws-ec2" ]]; then
-  if [[ $DIRECTOR_CPI != "aws" ]]; then
-    echo "Not targeting an AWS BOSH. Please use 'bosh target' before running this script."
-    exit 1
-  fi
+if [[ $infrastructure = "aws" && ${DIRECTOR_CPI} != "aws" ]]; then
+  fail "Not targeting an AWS BOSH. Please make sure you have run 'bosh target' and are targeting an AWS BOSH before running this script."
+  exit 1
 fi
 
 function latest_uploaded_stemcell {
@@ -40,10 +50,9 @@ function latest_uploaded_stemcell {
 }
 
 STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
-if [[ "${STEMCELL}X" == "X" ]]; then
+if [[ -z ${STEMCELL} ]]; then
   echo
   echo "Uploading latest $DIRECTOR_CPI/$STEMCELL_OS stemcell..."
-  STEMCELL_URL=$(bosh public stemcells --full | grep $DIRECTOR_CPI | grep $STEMCELL_OS | sort -nr | head -n1 | awk '{ print $4 }')
   bosh upload stemcell $STEMCELL_URL
 fi
 STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
